In [6]:
from sentence_transformers import SentenceTransformer,util
model = SentenceTransformer('all-MiniLM-L6-v2')

Downloading:   0%|          | 0.00/1.18k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/190 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/10.6k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/612 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/116 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/39.3k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/112 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/466k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/350 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/13.2k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/232k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/349 [00:00<?, ?B/s]

In [7]:
sentences = ['This framework generates embeddings from input sentence',
            'sentences are list of strings']

embeddings = model.encode(sentences)
embeddings.shape


(2, 384)

In [11]:
for sentence, embedding in zip(sentences, embeddings):
    print(sentence,'\n', embedding[:5],'\n', embedding.shape)

This framework generates embeddings from input sentence 
 [-0.02806348 -0.02237359 -0.00474183  0.02845586  0.04651126] 
 (384,)
sentences are list of strings 
 [ 0.04024431  0.0650033   0.05060358  0.05312231 -0.02137426] 
 (384,)


In [12]:
emb1 = model.encode('i am eating apple')
emb2 = model.encode('i like fruits')

cos_sim = util.cos_sim(emb1, emb2)
print(cos_sim)

tensor([[0.5398]])


In [16]:
# Compute cosine similarity between all pairs

sentences = ['A man is eating food.',
          'A man is eating a piece of bread.',
          'The girl is carrying a baby.',
          'A man is riding a horse.',
          'A woman is playing violin.',
          'Two men pushed carts through the woods.',
          'A man is riding a white horse on an enclosed ground.',
          'A monkey is playing drums.',
          'Someone in a gorilla costume is playing a set of drums.'
          ]

embeddings = model.encode(sentences)
print(embeddings.shape)

cos_sim = util.cos_sim(embeddings, embeddings)
cos_sim.shape


(9, 384)


torch.Size([9, 9])

# Get top 5 closest pairs


In [25]:

all_sentence_combinations = []

for i in range(len(cos_sim)):
    for j in range(i+1, len(cos_sim)):
        all_sentence_combinations.append((cos_sim[i][j], i , j))

print(all_sentence_combinations)

[(tensor(0.7553), 0, 1), (tensor(-0.1050), 0, 2), (tensor(0.2474), 0, 3), (tensor(-0.0704), 0, 4), (tensor(-0.0333), 0, 5), (tensor(0.1707), 0, 6), (tensor(0.0476), 0, 7), (tensor(0.0630), 0, 8), (tensor(-0.0610), 1, 2), (tensor(0.1442), 1, 3), (tensor(-0.0809), 1, 4), (tensor(-0.0216), 1, 5), (tensor(0.1157), 1, 6), (tensor(0.0362), 1, 7), (tensor(0.0216), 1, 8), (tensor(-0.1088), 2, 3), (tensor(0.0217), 2, 4), (tensor(-0.0413), 2, 5), (tensor(-0.0928), 2, 6), (tensor(0.0231), 2, 7), (tensor(0.0247), 2, 8), (tensor(-0.0348), 3, 4), (tensor(0.0362), 3, 5), (tensor(0.7369), 3, 6), (tensor(0.0821), 3, 7), (tensor(0.1389), 3, 8), (tensor(-0.1654), 4, 5), (tensor(-0.0592), 4, 6), (tensor(0.1961), 4, 7), (tensor(0.2564), 4, 8), (tensor(0.0769), 5, 6), (tensor(-0.0380), 5, 7), (tensor(-0.0895), 5, 8), (tensor(0.0495), 6, 7), (tensor(0.1191), 6, 8), (tensor(0.6433), 7, 8)]


In [30]:
all_sentence_combinations = sorted(all_sentence_combinations, key = lambda x:x[0], reverse=True)

#top 5 similar pairs:
for score, i, j in all_sentence_combinations[:5]:
    print(f'{sentences[i], sentences[j], cos_sim[i][j]}')

('A man is eating food.', 'A man is eating a piece of bread.', tensor(0.7553))
('A man is riding a horse.', 'A man is riding a white horse on an enclosed ground.', tensor(0.7369))
('A monkey is playing drums.', 'Someone in a gorilla costume is playing a set of drums.', tensor(0.6433))
('A woman is playing violin.', 'Someone in a gorilla costume is playing a set of drums.', tensor(0.2564))
('A man is eating food.', 'A man is riding a horse.', tensor(0.2474))


# Semantic Search

In [31]:
from sentence_transformers import SentenceTransformer, util
model = SentenceTransformer('clips/mfaq')

Downloading:   0%|          | 0.00/1.65k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/190 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/3.74k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/778 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/117 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.11G [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/294 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/9.08M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/464 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/229 [00:00<?, ?B/s]

/Users/v0m01sk/miniconda3/envs/ml/lib/python3.7/site-packages/transformers/configuration_utils.py:370: UserWarning: Passing `gradient_checkpointing` to a config initialization is deprecated and will be removed in v5 Transformers. Using `model.gradient_checkpointing_enable()` instead, or if you are using the `Trainer` API, pass `gradient_checkpointing=True` in your `TrainingArguments`.
  "Passing `gradient_checkpointing` to a config initialization is deprecated and will be removed in v5 "


In [51]:
question = "<Q>How many models can I host on HuggingFace?"
answer_1 = "<A>All plans come with unlimited private models and datasets."
answer_2 = "<A>AutoNLP is an automatic way to train and deploy state-of-the-art NLP models, seamlessly integrated with the Hugging Face ecosystem."
answer_3 = "<A>Based on how much training data and model variants are created, we send you a compute cost and payment link - as low as $10 per job."


query_embedding = model.encode(question)
corpus_embedding = model.encode([answer_1, answer_2, answer_3])

print(util.semantic_search(query_embedding, corpus_embedding))

[[{'corpus_id': 0, 'score': 0.5646325945854187}, {'corpus_id': 2, 'score': 0.5142340660095215}, {'corpus_id': 1, 'score': 0.4730038642883301}]]


In [52]:
from transformers import pipeline
qa_model = pipeline("question-answering")
question = "How many models can I host on HuggingFace?"
context = "All plans come with unlimited private models and datasets."
qa_model(question = question, context = context)

No model was supplied, defaulted to distilbert-base-cased-distilled-squad and revision 626af31 (https://huggingface.co/distilbert-base-cased-distilled-squad).
Using a pipeline without specifying a model name and revision in production is not recommended.


{'score': 0.7017179131507874, 'start': 20, 'end': 29, 'answer': 'unlimited'}

### Clustering

In [100]:
from sklearn.cluster import KMeans
import numpy as np

embedder = SentenceTransformer("all-MiniLM-L6-v2")
# Corpus with example sentences
corpus = ['A man is eating food.',
          'A man is eating a piece of bread.',
          'Horse is eating grass.',
          'A man is eating pasta.',
          'A Woman is eating Biryani.',
          'The girl is carrying a baby.',
          'The baby is carried by the woman',
          'A man is riding a horse.',
          'A man is riding a white horse on an enclosed ground.',
          'A monkey is playing drums.',
          'Someone in a gorilla costume is playing a set of drums.',
          'A cheetah is running behind its prey.',
          'A cheetah chases prey on across a field.',
          'The cheetah is chasing a man who is riding the horse.',
          'man and women with their baby are watching cheetah in zoo'
          ]

corpus_embedding = embedder.encode(corpus)

corpus_embedding = corpus_embedding/np.linalg.norm(corpus_embedding,axis=1, keepdims=True)

In [111]:
clustering_model = KMeans(n_clusters=3)
clustering_model.fit(corpus_embedding)
cluster_assignment = clustering_model.labels_
cluster_assignment

array([2, 2, 1, 2, 2, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0], dtype=int32)

In [112]:
clustered_sentences = {}

for sentence_id, cluster_id in enumerate(cluster_assignment):
    if cluster_id not in clustered_sentences:
        clustered_sentences[cluster_id]=[]

    clustered_sentences[cluster_id].append(corpus[sentence_id])

clustered_sentences

{2: ['A man is eating food.',
  'A man is eating a piece of bread.',
  'A man is eating pasta.',
  'A Woman is eating Biryani.'],
 1: ['Horse is eating grass.',
  'A man is riding a horse.',
  'A man is riding a white horse on an enclosed ground.',
  'A monkey is playing drums.',
  'Someone in a gorilla costume is playing a set of drums.',
  'A cheetah is running behind its prey.',
  'A cheetah chases prey on across a field.',
  'The cheetah is chasing a man who is riding the horse.'],
 0: ['The girl is carrying a baby.',
  'The baby is carried by the woman',
  'man and women with their baby are watching cheetah in zoo']}